version: "3.3"

services:
  frontend:
    tty: true
    container_name: demonitor
    hostname: demonitor
    ports:
      - 3000:3000
    build:
      context: Frontend
      dockerfile: Dockerfile
    restart: always

    volumes:
      - ./Frontend:/app
    networks:
      - external
      - internal
      - web

  

networks:
  web:
    driver: bridge
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
